export const skills: string[] = [
    'JavaScript',
    'TypeScript',
    'React',
    'React Native',
    'Redux',
    'Zustand',
    'Mobex',
    'chat.js',
    'Vue.js',
    'Next.js',
    'nuxt.js',
    'Bootstrap',
    'TailwindCSS',
    'Material UI',
    'Shadchn',
    'Node',
    'Express.js',
    'MongoDB',
    'Git',
    'GitHub'
]
